version: '3.8'

services:
  bot_app:
    container_name: bot_app
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile-dev
    restart: always
    networks:
      - bot_network
    env_file:
      - envs/.env.app.dev
    volumes:
      - '../../alembic/versions:/app/alembic/versions'
    depends_on:
      - bot_db

  bot_db:
    image: postgres:15.2-alpine
    container_name: bot_db
    restart: always
    networks:
      - bot_network
    env_file:
      - envs/.env.db.dev
    ports:
      - ${BOT_DB_PORT}:5432
    volumes:
      - 'db_data:/var/lib/postgresql/data'

networks:
  bot_network:
    name: bot_network
    driver: bridge

volumes:
  db_data:
