version: '3.8'

services:
  bot:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile-dev
    restart: always
    env_file:
      - envs/.env.app.example
      - envs/.env.app

  db:
    image: postgres:15.2-alpine
    restart: always
    env_file:
      - envs/.env.db.example
      - envs/.env.db
    ports:
      - '5432:5432'
    volumes:
      - 'db_data:/var/lib/postgresql/data'

volumes:
  db_data:
