version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    restart: always
    env_file:
      - docker/dev/envs/.env.app

  db:
    image: postgres:15.2-alpine
    restart: always
    env_file:
      - docker/dev/envs/.env.db
    ports:
      - '5432:5432'
