"""role added

Revision ID: 724df53b15b7
Revises: af69ef71b71f
Create Date: 2023-05-14 17:41:04.443854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724df53b15b7'
down_revision = 'af69ef71b71f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.SmallInteger(), nullable=False))
    op.drop_constraint('user_first_name_key', 'user', type_='unique')
    op.drop_constraint('user_last_name_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_last_name_key', 'user', ['last_name'])
    op.create_unique_constraint('user_first_name_key', 'user', ['first_name'])
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
