version: '3.8'

services:
  bot:
    build:
      context: ../..
      dockerfile: docker/prod/Dockerfile-prod
    restart: always
    env_file:
      - envs/.env.app.prod
    volumes:
      - '../../alembic/versions:/app/alembic/versions'
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    restart: always
    env_file:
      - envs/.env.db.prod
    ports:
      - '5432:5432'
    volumes:
      - 'db_data:/var/lib/postgresql/data'

volumes:
  db_data:
