name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USERNAME}}
          key: ${{secrets.SERVER_SSH_PRIVATE_KEY}}
          port: 22
          script: |
            eval `ssh-agent -s`
            cd .ssh
            ssh-add github
            ssh dmk@10.8.0.2
            cd projects/invest_portfolio_pro_bot/
            git pull
            export BOT_DB_PORT=${{secrets.BOT_DB_PORT}}
            docker compose -f docker/dev/docker-compose-dev.yml up --build -d
